name: libunwind

on:
  push:
    branches: [ master ]
    paths:
      - 'libunwind/**'
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir libunwind/build && cd libunwind/build
        cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_C_FLAGS="-fPIC -DPS4 -D_LIBUNWIND_IS_BAREMETAL=1" -DCMAKE_CXX_FLAGS="-fPIC -DPS4 -D_LIBUNWIND_IS_BAREMETAL=1" -DLLVM_PATH="../../llvm" -DLIBUNWIND_USE_COMPILER_RT=YES -DLIBUNWIND_BUILD_32_BITS=NO -DLIBUNWIND_ENABLE_STATIC=ON -DLIBUNWIND_USE_COMPILER_RT=YES -DLIBUNWIND_ENABLE_SHARED=OFF .. && make
    - name: Create tarball
      run: |
        mkdir -p release/lib
        cp -r libunwind/build/lib/* release/lib/
        cd release
        tar -cvzf libunwind.tar.gz lib/*
    - name: Upload libunwind
      uses: actions/upload-artifact@v2
      with:
        name: libunwind.tar.gz
        path: release/libunwind.tar.gz
